# Generated by Django 3.1.1 on 2020-10-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(max_length=50)),
                ('img_desc', models.CharField(max_length=500, null=True)),
                ('image_file', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
