# Generated by Django 3.1.1 on 2020-10-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201017_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_title',
            new_name='title',
        ),
    ]
