# Generated by Django 3.1.1 on 2020-10-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_image_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='desc',
        ),
    ]
