# Generated by Django 3.1.1 on 2020-10-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201018_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
